In [2]:
#importing libraries needed for data analysis
import numpy as np
import pandas as pd

In [4]:
#reading the data
data=pd.read_excel("D:\Beinex\Python\Dataset-Kaggle\HotelCustomersDataset.xlsx")
data

,ID,Nationality,Age,DaysSinceCreation,NameHash,DocIDHash,AverageLeadTime,LodgingRevenue,OtherRevenue,BookingsCanceled,...,SRMediumFloor,SRBathtub,SRShower,SRCrib,SRKingSizeBed,SRTwinBed,SRNearElevator,SRAwayFromElevator,SRNoAlcoholInMiniBar,SRQuietRoom
0,1,PRT,51.0,150,0x8E0A7AF39B633D5EA25C3B7EF4DFC5464B36DB7AF375...,0x71568459B729F7A7ABBED6C781A84CA4274D571003AC...,45,371.0,105.3,1,...,0,0,0,0,0,0,0,0,0,0
1,2,PRT,NaN,1095,0x21EDE41906B45079E75385B5AA33287CA09DE1AB86DE...,0x5FA1E0098A31497057C5A6B9FE9D49FD6DD47CCE7C26...,61,280.0,53.0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,DEU,31.0,1095,0x31C5E4B74E23231295FDB724AD578C02C4A723F4BA2B...,0xC7CF344F5B03295037595B1337AC905CA188F1B5B3A5...,0,0.0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,FRA,60.0,1095,0xFF534C83C0EF23D1CE516BC80A65D0197003D27937D4...,0xBD3823A9B4EC35D6CAF4B27AE423A677C0200DB61E82...,93,240.0,60.0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,FRA,51.0,1095,0x9C1DEF02C9BE242842C1C1ABF2C5AA249A1EEB4763B4...,0xE175754CF77247B202DD0820F49407C762C14A603B3A...,0,0.0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83585,83586,ITA,54.0,0,0x68010434A46BA6CEAFFACF00B7B7CD0E1825DC56E68F...,0x0A4038E9AE1E4E5A14832BEACEC6BCBE2219F275B65C...,0,0.0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
83586,83587,IRL,47.0,0,0x6DE7954E6AF065D29EF5C57D0DC8120FBAE6753D2CCB...,0xC0654B6A53840DD95DAE429966EC16E2A11FB186CC7B...,109,327.1,277.5,0,...,0,0,0,0,1,0,0,0,0,0
83587,83588,IRL,53.0,0,0x533C977BA6D1D8DFAD8D8D4C2250236D16EFD17B9F35...,0x3DCBEB254247836015CA95F0BBF42E6AF6A158380663...,0,0.0,0.0,0,...,0,0,0,0,1,0,0,0,0,0
83588,83589,IRL,85.0,0,0x58B3CB1975F09BD89EDD4DED8F644D1CCBE6B29C10C7...,0xEB64E8E6820F421508B96820AA3BA49404C01D178FE3...,109,981.3,9.0,0,...,0,0,0,0,0,1,0,0,0,0
83589,83590,IRL,13.0,0,0x1F2AA8A78ABFCBF190BFFB7BF2D5489EDFECD95CA51F...,0x0E0612BCF1C120B841DD02B9C27DF50B332815EDBB6D...,0,0.0,0.0,0,...,0,0,0,0,0,1,0,0,0,0

In [28]:
#basic analysis of the data 
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83590 entries, 0 to 83589
Data columns (total 34 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID                    83590 non-null  int64
 1   Nationality           83590 non-null  object
 2   Age                   79811 non-null  float64
 3   DaysSinceCreation     83590 non-null  int64
 4   NameHash              83590 non-null  object
 5   DocIDHash             83590 non-null  object
 6   AverageLeadTime       83590 non-null  int64
 7   LodgingRevenue        83590 non-null  float64
 8   OtherRevenue          83590 non-null  float64
 9   BookingsCanceled      83590 non-null  int64
 10  BookingsNoShowed      83590 non-null  int64
 11  BookingsCheckedIn     83590 non-null  int64
 12  PersonsNights         83590 non-null  int64
 13  RoomNights            83590 non-null  int64
 14  DaysSinceLastStay     83590 non-null  int64
 15  DaysSinceFirstStay    83590 non-null  int64
 16  DistributionChannel   83590 non-null  object
 17  MarketSegment         83590 non-null  object
 18  SRHighFloor           83590 non-null  int64
 19  SRLowFloor            83590 non-null  int64
 20  SRAccessibleRoom      83590 non-null  int64
 21  SRMediumFloor         83590 non-null  int64
 22  SRBathtub             83590 non-null  int64
 23  SRShower              83590 non-null  int64
 24  SRCrib                83590 non-null  int64
 25  SRKingSizeBed         83590 non-null  int64
 26  SRTwinBed             83590 non-null  int64
 27  SRNearElevator        83590 non-null  int64
 28  SRAwayFromElevator    83590 non-null  int64
 29  SRNoAlcoholInMiniBar  83590 non-null  int64
 30  SRQuietRoom           83590 non-null  int64
 31  Total_revenue         83590 non-null  float64
 32  Sumof                 83590 non-null  float64
 33  No_of_vists           83590 non-null  int64
dtypes: float64(5), int64(24), object(5)
memory usage: 21.7+ MB

In [22]:
data['Total_revenue']=data['LodgingRevenue']+data['OtherRevenue']
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83590 entries, 0 to 83589
Data columns (total 32 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID                    83590 non-null  int64
 1   Nationality           83590 non-null  object
 2   Age                   79811 non-null  float64
 3   DaysSinceCreation     83590 non-null  int64
 4   NameHash              83590 non-null  object
 5   DocIDHash             83590 non-null  object
 6   AverageLeadTime       83590 non-null  int64
 7   LodgingRevenue        83590 non-null  float64
 8   OtherRevenue          83590 non-null  float64
 9   BookingsCanceled      83590 non-null  int64
 10  BookingsNoShowed      83590 non-null  int64
 11  BookingsCheckedIn     83590 non-null  int64
 12  PersonsNights         83590 non-null  int64
 13  RoomNights            83590 non-null  int64
 14  DaysSinceLastStay     83590 non-null  int64
 15  DaysSinceFirstStay    83590 non-null  int64
 16  DistributionChannel   83590 non-null  object
 17  MarketSegment         83590 non-null  object
 18  SRHighFloor           83590 non-null  int64
 19  SRLowFloor            83590 non-null  int64
 20  SRAccessibleRoom      83590 non-null  int64
 21  SRMediumFloor         83590 non-null  int64
 22  SRBathtub             83590 non-null  int64
 23  SRShower              83590 non-null  int64
 24  SRCrib                83590 non-null  int64
 25  SRKingSizeBed         83590 non-null  int64
 26  SRTwinBed             83590 non-null  int64
 27  SRNearElevator        83590 non-null  int64
 28  SRAwayFromElevator    83590 non-null  int64
 29  SRNoAlcoholInMiniBar  83590 non-null  int64
 30  SRQuietRoom           83590 non-null  int64
 31  Total_revenue         83590 non-null  float64
dtypes: float64(4), int64(23), object(5)
memory usage: 20.4+ MB

In [25]:
data['Sumof']=data.groupby('NameHash')['Total_revenue'].transform('sum')
data['No_of_vists']=data.groupby('NameHash')['NameHash'].transform('count')
len(data)
x=data[data['No_of_vists']>=2]
len(x)

5207